[build]
publish = "public"
command = "hugo  --gc --config config.production.toml"

[context.production.environment]
HUGO_VERSION = "0.53"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.53"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.53"

[context.branch-deploy]
command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.53"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# A basic redirect rule
[[redirects]]
  from = "https://yourdomainname.netlify.com/*"
  to = "https://www.yoursite.com/:splat"

  # The default HTTP status code is 301, but you can define a different one.
  status = 301

  # By default, redirects won't be applied if there's a file with the same 
  # path as the one defined in the `from` property. Setting `force` to `true` 
  # will make the redirect rule take precedence over any existing files.
  force = true
